### ISSUE TITLE
Update wiki?

### ISSUE THREAD

**Issue by l300lvl** [voidlinux/voidlinux.github.com#14]
The wiki is seemingly very outdated. Using the google groups forum I was finally able to find out how to partition after 6 hours of the live installer complaining. Can we at least update the wiki to include the info explaining https://groups.google.com/forum/#!topic/voidlinux/_6Y28ifqnM0

Which is to use cfdisk to create your initial partitioning layout before trying to install, else the installer just fails and says use parted/gpart

**Comment by xtraeme** [comment]
The wiki is open to anyone with a github account, feel free to update it accordingly.

**Comment by l300lvl** [comment]
i did so, sorry i did not see it was so easy to do. i used the edit wiki rules to fix my mistake. that needs some love to. https://github.com/voidlinux/documentation/wiki/Installer-Partitioning is what i updated with a small note.

sorry for not noticing an edit button, ive never used wikis on here before :D

**Comment by xtraeme** [comment]
Thanks :+1:
