### ISSUE TITLE
decentral management of voidlinux.{eu,fr,com,net,us,org,de...} is becoming a real mess

### ISSUE THREAD

**Issue by Gottox** [voidlinux/voidlinux.github.com#15]
Maybe it's my OCD, but I find this really annoying: Currently we have at least 4 different people managing domains for void.

Some subdomains are only reachable through certian tlds, some people use {musl,}repo.voidlinux.\* to publish their own packages. (See https://github.com/voidlinux/void-packages/pull/1705)

It's a mess.

I strongly encourage you to move all domains to @xtraeme and donate the money to him instead. This way we can apply one zonefile to all domains, this reduces overhead and the danger of people messing around with their domains.

**Comment by Ypnose** [comment]
For now, I'll manage my .fr. I can perfectly do it without breaking anything. As always, things will be much clearer if there is coordination (which is missing ATM).

**Comment by the-maldridge** [comment]
This is fairly obsolete now, for future coordination please see voidlinux/void-infrastructure#10
