### ISSUE TITLE
download: verify key output: the full fingerprint is missing

### ISSUE THREAD

**Issue by weakish** [voidlinux/voidlinux.github.com#35]
http://www.voidlinux.eu/download/

```sh
$ LANG=C gpg --verify sha256sums.txt.asc
gpg: Signature made Sun Feb  8 12:33:05 2015 CET using RSA key ID 482F9368
gpg: Good signature from "Juan RP <xtraeme@gmail.com>" [unknown]
gpg:                 aka "[jpeg image of size 3503]" [unknown]
```

Only (short) `key ID` is included.
The short key ID is not reliable.
A MIM attack is still possible if they managed to generate a key ending `482F 9368`
(generating collision for short key is not very hard).

The full key finger print `Primary key fingerprint:` should be included.

**Comment by chneukirchen** [comment]
The full finger print is 6 lines above...
