### ISSUE TITLE
Wrong SSL certificate at voidlinux.eu

### ISSUE THREAD

**Issue by dutsky** [voidlinux/voidlinux.github.com#37]
When I trying to open voidlinux.eu via HTTPS I getting error about wrong certificate:
`This server could not prove that it is www.voidlinux.eu; its security certificate is from www.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.`

Is it possible to get a cert for *.voidlinux.eu?

**Comment by Gottox** [comment]
We host our pages at github, so we can't do anything about it till github fixes this situation.

see https://github.com/isaacs/github/issues/156
