### ISSUE TITLE
Installer won't allow for installation on nvme drives

### ISSUE THREAD

**Issue by Parentheseas** [voidlinux/voidlinux.github.com#42]
I tried to install void earlier, and going through the installer it will only recognize /dev/sdax devices, but no /dev/nvmex devices. The drive is visible and working properly, seen in another terminal instance. I apologize, I do not have any other information, but I can get it if need be.

**Comment by chneukirchen** [comment]
Wrong repo, please report at https://github.com/voidlinux/void-mklive.

show_disks in installer.sh.in will need tweaking.
