### ISSUE TITLE
Misinformation on the frontpage

### ISSUE THREAD

**Issue by unixsheikh** [voidlinux/voidlinux.github.com#56]
On the frontpage (index.html) it says:

```
Install once, update daily. Your system will always be up-to-date.
```

This simply isn't correct. It heavily depends upon whether or not the packages you're using has an active maintainer as Void doesn't have a security team or "upgrade team".

There exists a bunch of orphaned packages that haven't been updated for ages. Samba, for example, is still 3.6 and contains several bugs and security issues.

People need to be made aware on how these things are run in Void and that Void is lacking maintainers.

I didn't want to do a PR as I think it needs to be discussed first how to formulate and address this issue in the best manner.

Kind regards

**Comment by unixsheikh** [comment]
I agree, misinformation was a bad choice of word. Hmm. How about expanding the sentence with a parentheses that can be removed again if the project reaches a level of maintenance where the statement is correct?

Install once, update daily. Your system will always be up-to-date (currently we're lacking maintainers and as such not all packages are kept up to date. If you would like to help please see INSERT LINK).

**Comment by unixsheikh** [comment]
Also I think it would be really great if we could branch packages into maintained and orphaned packages, or two separate repos, so that orphaned packages are removed from xbps-install. I don't know how long a package should be located in the system, but I think it's really dangerous to keep orphaned packages in the install system. People are unaware and are installing packages with unaddressed security issues - such as the samba package for example.

On FreeBSD someone is assigned to look for non-updated packages, it's his task and responsibility (a couple of people actually - I know we're lacking people). When a package is found not upgraded an email is sent to the maintainer and if he doesn't respond or update the package, it eventually gets removed.

**Comment by the-maldridge** [comment]
@Gottox I believe the wording carries the intended meaning.  I do not believe any reasonable English speaker would read that in terms of absolutes, instead it would be taken to mean that there is not additional action needed by the consumer to ensure updates would be obtained.

**Comment by Vaelatern** [comment]
I don't think this needs addressing.
