### ISSUE TITLE
Suggestion: New project management

### ISSUE THREAD

**Issue by unixsheikh** [voidlinux/voidlinux.github.com#57]
Please consider this issue as a suggestion with the best intentions and bear with any misunderstandings on my part.

We're a couple of guys who have been discussing this issue and IMHO Void Linux is lacking information about project goals, membership guidelines, and a good/proper management procedure.

As an inspiration take a look at the Parabola website. I'm NOT saying that Void should be like that, I am just using the Parabola project and website as an example to better illustrate my point (I hope).

First, there is the social contract:

- https://wiki.parabola.nu/Parabola_Social_Contract

Second, a clear list of developers, support.. i.e.:

- https://www.parabola.nu/people/hackers/ 
- https://www.parabola.nu/people/support-staff/
- https://www.parabola.nu/people/hacker-fellows/

Third, a list of how to help. This gives potential new-comers a better chance of determining whether Parabola is a project they would like to invest future time in:

- https://wiki.parabola.nu/How_to_help

Currently Void feels like the "hobby" project of a bunch of developers with no serious desire to grow neither its user base nor its maintainer/developer base. And if that is the case, then that is fine, but if that isn't the case, and there exist a desire among the developers to grow Void into something more than what it is, then I suggest we change how things are managed.

First we need some kind of decision process and leadership. Then we need the currently active developers (I know you are all very busy) to decide upon some basic goals of the project and then make a list on the website about what you specifically need help with and how people can contribute. We - and each developer - need rules and guidelines for what gets accepted and what doesn't so that these things isn't up to who ever feels like it.

We need guidelines - in writing - about criteria for accepting packages, like when is a package okay to become accepted into Void and rules about when a package gets taken out because of a non-responsive maintainer. Regarding this I recommend looking at the rules and guidelines from the FreeBSD project for port/package maintainers.

Currently everyone's answer to everything is, make a PR, and while that might work for some minor stuff, it doesn't work for proper project management.

Someone has also raised the concern that all the above would only result in more work for the current developers, but until some of the solutions presented above is implemented I don't think many people would consider chipping in because it's very difficult to get a feel for where Void is heading.

A developer only forum or mailing list could also be a good idea for developers to organize stuff between themselves, vote on specific issues, address important security concerns etc.

These issues are what I believe needs to be addressed in order for Void to grow and getting more people involved, etc.

And no, I'm not talking about making Void the next Debian project. But I think the project needs to strike a balance between how things are managed in OpenBSD, with way to much dictatorship, and then in Debian, with way to much bureaucracy. Something like FreeBSD would be really great.

Kind regards.

**Comment by unixsheikh** [comment]
Either you haven't read what I wrote or you have completely misunderstood the whole ticket, but thanks for you comment.

**Comment by unixsheikh** [comment]
In the light of the issues addressed on https://www.voidlinux.eu/news/2018/05/serious-issues.html I re-open this issue just in case other comments and ideas find their way to this place. Also relevant: https://forum.voidlinux.eu/t/feedback-channel-about-void-linux-management-issues/5457

**Comment by the-maldridge** [comment]
Github is not a forum, in the event you wish to discuss the project or its operations, please join us at irc.freenode.net #voidlinux which is a logged channel.

As I have no desire to debate this further here, I am locking this issue.

**Comment by Vaelatern** [comment]
Normally a suggestion of new project management against the wishes of the current project management is called a "fork". 

If you want things run differently, then feel free.
