### ISSUE TITLE
Info: New Void mirror

### ISSUE THREAD

**Issue by unixsheikh** [voidlinux/voidlinux.github.com#58]
Hi Void Linux

mirrors.dotsrc.org now hosts a mirror of your project:
ftp|rsync|http|https://mirrors.dotsrc.org/voidlinux/
Our servers are located at Aalborg University in Denmark. We got a 10Gbit
connection, so feel free to send some traffic our way.

We pull once every 4 hours from rsync://repo.voidlinux.eu/voidmirror/

Best regards
Anders Trier
dotsrc.org

> Hi,
>
> Void Linux is a great independent Linux distribution created in 2008
> and I think it would be fantastic if it could be mirrored on dotsrc.org.
>
> The distribution is growing, but isn't that big still, but it's quite
> fantastic and deserves some help :)
>
> Take a look at the project website:
>
> https://www.voidlinux.eu/
>
> Thanks in advance.
>
> Kindest regards

**Comment by the-maldridge** [comment]
This is a very incomplete mirror at the moment, are you intentionally not mirroring the current/ subtree?  Please note that that subtree is available via a symlink so you will need specific rsync options to follow links.

**Comment by unixsheikh** [comment]
You need to address this to dotsrc.org. I have just forwarded the message.

**Comment by the-maldridge** [comment]
Contacted dotsrc.org directly.
