### ISSUE TITLE
ERROR: No module named ‘ConfigParser’ in fail2ban

### ISSUE THREAD

**Issue by JohnSPeach** [voidlinux/voidlinux.github.com#59]
fail2ban 0.10 will no longer run with python3, giving the above error. 0.11 does not have this problem. It is because ConfigParser has been replaced by configparser.

**Comment by asergi** [comment]
Wrong repo. Anyway, Python 3 support should be fixed in `fail2ban-0.10.3.1_2`.

> It is because ConfigParser has been replaced by configparser.

That's correct. The ConfigParser module has been renamed to configparser in Python 3.
