### ISSUE TITLE
Homepage update | "New package" entry on top right leads to non-existing link right now

### ISSUE THREAD

**Issue by rubyFeedback** [voidlinux/voidlinux.github.com#63]
First, I actually preferred the old one. ;)

This is partially due to me being lazy, but also partially because I think it was easier
to find what I was looking for there - mostly updates.

Anyway, ignoring this, the new homepage has an update box on the top right side.

In it you can see, right now, something like this:

"New package | any"

Precisely that.

The "any" part is a link to github and when I click on it I am redirected to this page:

https://github.com/void-linux/void-packages/blob/master/srcpkgs/New%20package

Which does not exist.

I assume something is automatically generated? But not found.

EITHER way, I propose that if a completely new package is shown, that the NAME of the program is also shown. This could then be:

"New package (foobar)"

Or it could be the name first, and then an indicator that it is new.

Right now the functionality seems to not work very well (which I assume may be the case after any homepage is updating but I am not putting any blame, I am merely reporting that it presently does not work perfectly well.

Thanks for reading - feel free to close this issue at any moment in time.

**Comment by the-maldridge** [comment]
Not a Bug.
